CREATE TABLE [dbo].[FoulType]
(
	[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(255) NOT NULL, 
    [Description] NVARCHAR(255) NULL, 
    [UIKey] NVARCHAR(20) NOT NULL DEFAULT ''
)
