CREATE TABLE [dbo].[GameEvent]
(
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [EventTypeID] UNIQUEIDENTIFIER NOT NULL, 
    [Description] NVARCHAR(500) NULL, 
    [PlayerID] UNIQUEIDENTIFIER NOT NULL, 
    [TeamID] UNIQUEIDENTIFIER NULL, 
    [TimeStamp] DATETIME NOT NULL, 
    [GameID] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_GameEvents_GameEventTypes] FOREIGN KEY ([EventTypeID]) REFERENCES [GameEventType]([ID]), 
    CONSTRAINT [FK_GameEvents_Players] FOREIGN KEY ([PlayerID]) REFERENCES [Player]([ID]), 
    CONSTRAINT [FK_GameEvents_Teams] FOREIGN KEY ([TeamID]) REFERENCES [Team]([ID]), 
    CONSTRAINT [FK_GameEvents_Games] FOREIGN KEY ([GameID]) REFERENCES [Game]([ID])
)
